### ISSUE TITLE
PR관리는 별도로 하지 않는건가요?

### ISSUE THREAD

**Issue by mirusu400** [gunh0/kr-vulhub#187]
안녕하세요.

vulhub 검색하다가 이 Repo가 있어서 좀 살펴봤는데, PR에 WHS 분들이 공부하셔서 올린게 2023년부터 몇백개씩 쌓여있는데 정작 머지된건 거의 초창기 3개밖에 없더라고요.

여긴 온전히 WHS 공부 목적의 레포인가요? 아니면 vulhub를 대체하기 위해서 한 프로젝트인가요?

전자라면 About과 README를 WHS 이외 유저분들이 헷갈리지 않도록 수정을 제안드리고, 후자라면 적어도 프로젝트 PR이라도 좀 관리해주실수 있을까요?

감사합니다.

**Comment by gunh0** [comment]
처음엔 온전히 오픈소스처럼 대체하려는 목적이였으나, 대부분의 PR 이 제대로 검증되지 않은(동작하지 않는) 채로 올라오는 경우가 많았습니다.

결국 하나씩 재검증하려다보니 각기 다른 환경에서 올라오는 base 이미지에 대한 정보조차도 모르는 채로 한사람이 관리한다는게 현실적으로 불가능한 일이되어서 우선은 공부 목적의 레포로 둘 생각입니다.
추후 여력이 되는대로 수정해나가면 좋겠네요.

관리에 욕심이 있는 분들을 대상으로 모집도 진행했었으나, 그마저도 잘 구해지지 않았던지라 (Git부터 제대로 잘 응용하고 다루실줄 아는 분들이 적었던...) 교육생들 사이에서는 쉽지 않았던 것 같습니다.

이번 기수의 경우에도 애초 과제를 제출하신분들도 적었기도 해서 해당 과제를 계속 제출하는게 맞는지도 좀 혼란스러운 상황이라 관리되지 않고 있는점 양해부탁드립니다 ㅎㅎ
고민해보고, 여력이되는 때에 같이 관리할 멤버를 사이드 프로젝트로 진행하는 식으로라도 정리해보겠습니다.

좋은 피드백 감사합니다~
